### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by GhostlyDark** [DemoXinMC/Multiworld64#4]
This might be difficult to reproduce as it happens randomly.

Picking up an item for another player can cause the player to pick the item over and over again whenever the player that receives the item enters a new area. That player can't receive any new items from other players anymore. Resetting the game doesn't help much, as the player still can't receive any new items outside of his own save. This likely renders the seed unplayable.

Encountered this with two different seeds. Both had 3 players and it both started happening around 200 items in total.

**Comment by Sparky7198** [comment]
I've had this same Issue too. It happened right after i crashed after i received an Ice trap from my friend but he couldn't receive anything else from me anymore. Strangely though i suggested him to start a second file in the same seed and they managed to receive all the items that didn't go through in the first file. but they still didn't go to the first file after saving on the second. So its not a connection issue but a file issue?
